### PR TITLE
Update Gradle wrapper and plugin

### PR DESCRIPTION
**Pull request by friederbluemle**
Two quick updates here:

- Latest stable Gradle wrapper `4.8.1`
- Latest Android Gradle plugin `3.1.3`

Note that `buildToolsVersion` was removed since the newer version of the Gradle plugin automatically selects the right version:

```
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

### CODE REVIEW

**Comment by 109021017** [comment]
Vector drawables is only used in api 25 and upper which fully support vector drawables by default. So no need to add `vectorDrawables.useSupportLibrary = true`.

**Comment by friederbluemle** [comment]
@109021017 Thanks for the response. I tried to remove the line, and this is the error I'm getting:

```
> Task :app:mergeDebugResources FAILED
Error: There were multiple failures while executing work items

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> There were multiple failures while executing work items
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
> A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
> Error while processing [...]/app/src/main/res/drawable/layers.xml : Can't process attribute android:fillColor="@color/colorPrimary": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
```

Any ideas?

**Comment by friederbluemle** [comment]
Gradle `4.8.1` is now available. I amended my commit and updated this PR.

Still looking for an alternative for the vector drawables declaration.. @109021017 Thanks

**Comment by 109021017** [comment]
fix `vectorDrawables.useSupportLibrary = true` problem in f6bf9d280e13dc1ea9a1988865ed2adf65c75df1

**Comment by friederbluemle** [comment]
Great! 🙇

**Pull request merged**
